name = "ExperimentalAPI"
uuid = "fd2d14cb-3a46-42a9-afd8-e8499236f05e"
version = "0.1.1"
authors = ["sota shimozono <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extensions]
ExperimentalAPITestExt = "Test"

[compat]
Aqua = "0.8"
TOML = "1"
Test = "1"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
